server:
  port: ${SERVER_PORT:8082}
spring:
  application:
    name: CarRentalSystem

  profiles:
    active: ${SPRING_PROFILE:local}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5433/carrentalsystem}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:123}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:  update
    show-sql: true
  hateoas:
    use-hal-as-default-json-media-type: false

  data:
    rest:
      default-media-type: application/json
